version: "3.6"
services:
  web:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    command: npm run dev
