name: Deploy Next.js Site with Zero Downtime

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Generate Deployment Timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'out'
        DEST_DIR: ${{ steps.timestamp.outputs.timestamp }}

    - name: Update CloudFront Origin Path
      run: |
        aws cloudfront update-distribution --id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --distribution-config '{
          "Origins": {
            "Items": [
              {
                "Id": "myS3Origin",
                "DomainName": "${{ secrets.S3_BUCKET_NAME }}.s3.amazonaws.com",
                "OriginPath": "/${{ steps.timestamp.outputs.timestamp }}"
              }
            ]
          },
          "DefaultCacheBehavior": {
            "TargetOriginId": "myS3Origin"
          },
          "CallerReference": "${{ steps.timestamp.outputs.timestamp }}",
          "Comment": "Deployment ${$ steps.timestamp.outputs.timestamp }}",
          "Enabled": true
        }'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'

